package main

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/fjaeckel/open-aircrew-rules/credentials"
)

// topN is how many entries each "most depended on" list shows.
const topN = 10

// dependenciesFile renders docs/dependencies.md: the requires and uses graphs as Mermaid
// diagrams per authority, a per-credential table and the most depended-on entries.
func dependenciesFile(cat *credentials.Catalogue) []byte {
	d := cat.Dependencies()
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	p("<!-- Code generated by rulesgen. DO NOT EDIT. -->\n\n")
	p("# Credential dependencies\n\n")
	p("Generated from `credentials/` by `go generate ./...`. Both graphs are acyclic, and a shared\n")
	p("evaluation never uses a credential's evaluation; the gate fails otherwise (DESIGN.md\n")
	p("section 3). Look here before changing a shared evaluation: everything that uses it changes.\n\n")
	p("%d credentials, %d shared evaluations, %d requires edges, %d uses edges.\n\n", len(cat.Credentials), len(cat.Shared), len(d.Requires), len(d.Uses))
	p("## Legend\n\n")
	p("- **Requires**: credential to credential. Solid arrow: `requires_all`; dashed arrow:\n")
	p("  `requires_any`.\n")
	p("- **Uses**: a credential borrows an evaluation. Its evaluations are collapsed into one\n")
	p("  node; hexagons are shared evaluations, rectangles with `#` a credential's evaluation.\n")
	p("  The table below lists each evaluation.\n\n")

	auths := authorities(cat)
	p("## Requires\n")
	for _, a := range auths {
		g := newDiagram()
		for _, r := range d.Requires {
			if authority(r.From) != a {
				continue
			}
			arrow := "-->"
			if r.Any {
				arrow = "-.->"
			}
			g.edge(cat, r.From, arrow, r.To)
		}
		p("%s", g.render(a))
	}

	p("\n## Uses\n")
	for _, a := range auths {
		g := newDiagram()
		for _, u := range d.Uses {
			if authority(u.From) != a {
				continue
			}
			from, _, _ := strings.Cut(u.From, "#")
			if _, ok := cat.Shared[u.From]; ok {
				from = u.From
			}
			g.edge(cat, from, "-->", u.To)
		}
		p("%s", g.render(a))
	}

	p("\n## By credential\n\n")
	p("| Credential | Requires all | Requires any | Uses (evaluation: from) |\n")
	p("| --- | --- | --- | --- |\n")
	ids := make([]string, 0, len(cat.Credentials))
	for _, c := range cat.Credentials {
		ids = append(ids, c.ID)
	}
	sort.Strings(ids)
	for _, id := range ids {
		var all, anyOf, uses []string
		for _, r := range d.Requires {
			if r.From != id {
				continue
			}
			if r.Any {
				anyOf = appendNew(anyOf, code(r.To))
			} else {
				all = appendNew(all, code(r.To))
			}
		}
		for _, u := range d.Uses {
			if c, e, _ := strings.Cut(u.From, "#"); c == id {
				uses = append(uses, fmt.Sprintf("%s: %s", code(e), code(u.To)))
			}
		}
		p("| %s | %s | %s | %s |\n", code(id), strings.Join(all, ", "), strings.Join(anyOf, ", "), strings.Join(uses, "<br>"))
	}

	shared := map[string]int{}
	creds := map[string][2]int{}
	for _, r := range d.Requires {
		n := creds[r.To]
		n[0]++
		creds[r.To] = n
	}
	for _, u := range d.Uses {
		if c, _, ok := strings.Cut(u.To, "#"); ok {
			n := creds[c]
			n[1]++
			creds[c] = n
		} else {
			shared[u.To]++
		}
	}
	p("\n## Most depended on\n\n")
	p("Shared evaluations by the evaluations that use them:\n\n| Shared evaluation | Used by |\n| --- | --- |\n")
	for _, id := range byCount(shared, func(id string) int { return shared[id] }) {
		p("| %s | %d |\n", code(id), shared[id])
	}
	total := func(id string) int { return creds[id][0] + creds[id][1] }
	p("\nCredentials by the requirements naming them and the evaluations borrowing theirs:\n\n")
	p("| Credential | Required by | Borrowed by | Total |\n| --- | --- | --- | --- |\n")
	for _, id := range byCount(creds, total) {
		p("| %s | %d | %d | %d |\n", code(id), creds[id][0], creds[id][1], total(id))
	}
	return []byte(b.String())
}

// byCount returns up to topN keys of m, highest count first, then by id.
func byCount[V any](m map[string]V, count func(string) int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if ci, cj := count(keys[i]), count(keys[j]); ci != cj {
			return ci > cj
		}
		return keys[i] < keys[j]
	})
	if len(keys) > topN {
		keys = keys[:topN]
	}
	return keys
}

func authorities(cat *credentials.Catalogue) []string {
	var out []string
	for _, c := range cat.Credentials {
		out = appendNew(out, authority(c.ID))
	}
	sort.Strings(out)
	return out
}

func authority(id string) string {
	a, _, _ := strings.Cut(id, ".")
	return a
}

// diagram is one Mermaid flowchart: each node declared once, then the distinct edges.
type diagram struct {
	nodes map[string]string
	edges []string
	seen  map[string]bool
}

func newDiagram() *diagram { return &diagram{nodes: map[string]string{}, seen: map[string]bool{}} }

func (g *diagram) edge(cat *credentials.Catalogue, from, arrow, to string) {
	g.nodes[from] = nodeDecl(cat, from)
	g.nodes[to] = nodeDecl(cat, to)
	e := fmt.Sprintf("  %s %s %s", mermaidID(from), arrow, mermaidID(to))
	if !g.seen[e] {
		g.seen[e] = true
		g.edges = append(g.edges, e)
	}
}

func (g *diagram) render(authority string) string {
	if len(g.edges) == 0 {
		return ""
	}
	ids := make([]string, 0, len(g.nodes))
	for id := range g.nodes {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var b strings.Builder
	fmt.Fprintf(&b, "\n### %s\n\n```mermaid\nflowchart LR\n", strings.ToUpper(authority))
	for _, id := range ids {
		fmt.Fprintf(&b, "  %s\n", g.nodes[id])
	}
	fmt.Fprintf(&b, "%s\n```\n", strings.Join(g.edges, "\n"))
	return b.String()
}

// nodeDecl declares a Mermaid node: a credential, a credential's evaluation or (hexagon) a
// shared evaluation.
func nodeDecl(cat *credentials.Catalogue, id string) string {
	label := strings.ReplaceAll(id, "#", "#35;")
	if _, ok := cat.Shared[id]; ok {
		return fmt.Sprintf("%s{{%q}}", mermaidID(id), label)
	}
	return fmt.Sprintf("%s[%q]", mermaidID(id), label)
}

func mermaidID(id string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return '_'
	}, id)
}

func code(s string) string { return "`" + s + "`" }

func appendNew(l []string, s string) []string {
	for _, x := range l {
		if x == s {
			return l
		}
	}
	return append(l, s)
}
