// Command rulesgen generates Go from vocabulary.yaml, messages/keys.yaml and the credential
// catalogue: engine/zz_metrics_gen.go (the metric dispatch the engine must implement),
// gen/constants.go (credential and evaluation ids, message keys, metric names), one test
// file per credential under gen/ that runs its worked examples, and docs/dependencies.md
// (the requires and uses graphs). Run it with `go generate ./...`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/fjaeckel/open-aircrew-rules/credentials"
	"github.com/fjaeckel/open-aircrew-rules/engine"
)

const header = "// Code generated by rulesgen. DO NOT EDIT.\n\n"

func main() {
	root := flag.String("root", ".", "module root (the directory holding vocabulary.yaml)")
	flag.Parse()
	if err := generate(*root); err != nil {
		log.Fatal(err)
	}
}

func generate(root string) error {
	cat, err := credentials.Load(root)
	if err != nil {
		return err
	}
	if err := write(filepath.Join(root, "engine", "zz_metrics_gen.go"), metricsFile(cat.Engine.Vocabulary)); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(root, "docs"), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, "docs", "dependencies.md"), dependenciesFile(cat), 0o644); err != nil {
		return err
	}
	genDir := filepath.Join(root, "gen")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return err
	}
	old, _ := filepath.Glob(filepath.Join(genDir, "credential_*_test.go"))
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	if err := write(filepath.Join(genDir, "constants.go"), constantsFile(cat)); err != nil {
		return err
	}
	if err := write(filepath.Join(genDir, "helpers_test.go"), helpersFile()); err != nil {
		return err
	}
	for _, c := range cat.Credentials {
		name := filepath.Join(genDir, "credential_"+snake(c.ID)+"_test.go")
		if err := write(name, credentialTestFile(c.ID)); err != nil {
			return err
		}
	}
	return nil
}

func credentialTestFile(id string) []byte {
	return []byte(fmt.Sprintf(header+`package gen_test

import "testing"

func TestCredential_%s(t *testing.T) { runCredentialExamples(t, %q) }
`, snake(id), id))
}

func write(path string, src []byte) error {
	out, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: %w\n%s", path, err, src)
	}
	return os.WriteFile(path, out, 0o644)
}

// ident turns a dotted, dashed or snake name into an exported Go identifier part.
func ident(s string) string {
	var b strings.Builder
	upper := true
	var prev rune
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper && unicode.IsDigit(r) && unicode.IsDigit(prev) {
			b.WriteRune('_')
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
		} else {
			b.WriteRune(r)
		}
		upper, prev = false, r
	}
	return b.String()
}

func snake(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return '_'
	}, s)
}

func sortedMetricNames(v *engine.Vocabulary) []string {
	names := make([]string, 0, len(v.Metrics))
	for n := range v.Metrics {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func metricsFile(v *engine.Vocabulary) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("package engine\n\n")
	b.WriteString("// metricImpl lists one method per vocabulary metric; metrics must implement all.\n")
	b.WriteString("type metricImpl interface {\n")
	names := sortedMetricNames(v)
	for _, n := range names {
		fmt.Fprintf(&b, "\tmetric%s(*%s) mv\n", ident(n), itemType(v.Metrics[n]))
	}
	b.WriteString("}\n\nvar _ metricImpl = metrics{}\n\n")
	b.WriteString("// flightMetricFuncs maps flight metric names to implementations.\n")
	b.WriteString("var flightMetricFuncs = map[string]func(*Flight) mv{\n")
	for _, n := range names {
		if itemType(v.Metrics[n]) == "Flight" {
			fmt.Fprintf(&b, "\t%q: metrics{}.metric%s,\n", n, ident(n))
		}
	}
	b.WriteString("}\n\n// eventMetricFuncs maps event metric names to implementations.\n")
	b.WriteString("var eventMetricFuncs = map[string]func(*Event) mv{\n")
	for _, n := range names {
		if itemType(v.Metrics[n]) == "Event" {
			fmt.Fprintf(&b, "\t%q: metrics{}.metric%s,\n", n, ident(n))
		}
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func itemType(m engine.MetricDef) string {
	if m.Source == "events" {
		return "Event"
	}
	return "Flight"
}

func constantsFile(cat *credentials.Catalogue) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("// Package gen holds generated constants and the per-credential example tests.\npackage gen\n\n")
	creds := make([]string, 0, len(cat.Credentials))
	for _, c := range cat.Credentials {
		creds = append(creds, c.ID)
	}
	sort.Strings(creds)
	b.WriteString("// Credential ids.\nconst (\n")
	for _, id := range creds {
		fmt.Fprintf(&b, "\tCredential%s = %q\n", ident(id), id)
	}
	evals := make([]string, 0, len(cat.ByEvaluation))
	for k, id := range cat.ByEvaluation {
		if id != "" {
			evals = append(evals, k)
		}
	}
	sort.Strings(evals)
	b.WriteString(")\n\n// Evaluation ids (<credential id>#<evaluation id>) that compile to a rule.\nconst (\n")
	for _, k := range evals {
		fmt.Fprintf(&b, "\tEvaluation%s = %q\n", ident(k), k)
	}
	b.WriteString(")\n\n// Message keys.\nconst (\n")
	keys := make([]string, 0, len(cat.Engine.Keys.Keys))
	for _, k := range cat.Engine.Keys.Keys {
		keys = append(keys, k.Key)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "\tKey%s = %q\n", ident(k), k)
	}
	b.WriteString(")\n\n// Metric names.\nconst (\n")
	for _, n := range sortedMetricNames(cat.Engine.Vocabulary) {
		fmt.Fprintf(&b, "\tMetric%s = %q\n", ident(n), n)
	}
	b.WriteString(")\n\n// CredentialIDs lists every credential id.\nvar CredentialIDs = []string{\n")
	for _, id := range creds {
		fmt.Fprintf(&b, "\tCredential%s,\n", ident(id))
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func helpersFile() []byte {
	return []byte(header + `package gen_test

import (
	"sync"
	"testing"

	"github.com/fjaeckel/open-aircrew-rules/credentials"
)

var credentialCatalogue = sync.OnceValues(func() (*credentials.Catalogue, error) { return credentials.Load("..") })

// runCredentialExamples runs every worked example in examples/<id>.yaml.
func runCredentialExamples(t *testing.T, id string) {
	t.Helper()
	cat, err := credentialCatalogue()
	if err != nil {
		t.Fatal(err)
	}
	files, err := credentials.LoadExamples("..")
	if err != nil {
		t.Fatal(err)
	}
	n := 0
	for _, f := range files {
		if f.Credential != id {
			continue
		}
		for _, x := range f.Examples {
			n++
			t.Run(x.Name, func(t *testing.T) {
				for _, d := range cat.RunExample(id, x) {
					t.Errorf("%s: %s", f.File, d)
				}
			})
		}
	}
	if n == 0 {
		t.Error("no worked examples")
	}
}
`)
}
