// Code generated by rulesgen. DO NOT EDIT.

package engine

// metricImpl lists one method per vocabulary metric; metrics must implement all.
type metricImpl interface {
	metricApproaches(*Flight) mv
	metricEvents(*Event) mv
	metricFlights(*Flight) mv
	metricFullStopLandings(*Flight) mv
	metricFullStopNightLandings(*Flight) mv
	metricHolds(*Flight) mv
	metricInterceptAndTrack(*Flight) mv
	metricLandingsNight(*Flight) mv
	metricLandingsTotal(*Flight) mv
	metricLaunches(*Flight) mv
	metricLongestFlightMinutes(*Flight) mv
	metricLongestTrainingFlightMinutes(*Flight) mv
	metricMinutesDual(*Flight) mv
	metricMinutesDualGiven(*Flight) mv
	metricMinutesDualOrSpic(*Flight) mv
	metricMinutesIfr(*Flight) mv
	metricMinutesInstructorOrExaminer(*Flight) mv
	metricMinutesPic(*Flight) mv
	metricMinutesPicOrDualOrSpic(*Flight) mv
	metricMinutesPicOrSpic(*Flight) mv
	metricMinutesSpic(*Flight) mv
	metricMinutesTotal(*Flight) mv
	metricMountainLandings(*Flight) mv
	metricNotRecorded(*Flight) mv
	metricRouteSectors(*Flight) mv
	metricTakeoffsNight(*Flight) mv
	metricTakeoffsNightPeriod(*Flight) mv
	metricTakeoffsTotal(*Flight) mv
	metricTakeoffsAndLandings(*Flight) mv
	metricTows(*Flight) mv
	metricTrainingFlights(*Flight) mv
}

var _ metricImpl = metrics{}

// flightMetricFuncs maps flight metric names to implementations.
var flightMetricFuncs = map[string]func(*Flight) mv{
	"approaches":                      metrics{}.metricApproaches,
	"flights":                         metrics{}.metricFlights,
	"full_stop_landings":              metrics{}.metricFullStopLandings,
	"full_stop_night_landings":        metrics{}.metricFullStopNightLandings,
	"holds":                           metrics{}.metricHolds,
	"intercept_and_track":             metrics{}.metricInterceptAndTrack,
	"landings.night":                  metrics{}.metricLandingsNight,
	"landings.total":                  metrics{}.metricLandingsTotal,
	"launches":                        metrics{}.metricLaunches,
	"longest_flight_minutes":          metrics{}.metricLongestFlightMinutes,
	"longest_training_flight_minutes": metrics{}.metricLongestTrainingFlightMinutes,
	"minutes.dual":                    metrics{}.metricMinutesDual,
	"minutes.dualGiven":               metrics{}.metricMinutesDualGiven,
	"minutes.dualOrSpic":              metrics{}.metricMinutesDualOrSpic,
	"minutes.ifr":                     metrics{}.metricMinutesIfr,
	"minutes.instructorOrExaminer":    metrics{}.metricMinutesInstructorOrExaminer,
	"minutes.pic":                     metrics{}.metricMinutesPic,
	"minutes.picOrDualOrSpic":         metrics{}.metricMinutesPicOrDualOrSpic,
	"minutes.picOrSpic":               metrics{}.metricMinutesPicOrSpic,
	"minutes.spic":                    metrics{}.metricMinutesSpic,
	"minutes.total":                   metrics{}.metricMinutesTotal,
	"mountain_landings":               metrics{}.metricMountainLandings,
	"not_recorded":                    metrics{}.metricNotRecorded,
	"route_sectors":                   metrics{}.metricRouteSectors,
	"takeoffs.night":                  metrics{}.metricTakeoffsNight,
	"takeoffs.night_period":           metrics{}.metricTakeoffsNightPeriod,
	"takeoffs.total":                  metrics{}.metricTakeoffsTotal,
	"takeoffs_and_landings":           metrics{}.metricTakeoffsAndLandings,
	"tows":                            metrics{}.metricTows,
	"training_flights":                metrics{}.metricTrainingFlights,
}

// eventMetricFuncs maps event metric names to implementations.
var eventMetricFuncs = map[string]func(*Event) mv{
	"events": metrics{}.metricEvents,
}
